# Your Solution
version: '3.8'

services:
  book_catalog:
    build: ./book_catalog
    image: projectpthree2024/book_catalog
    container_name: book_catalog
    environment:
      - DATABASE_URL=postgresql://sit722diva_user:PW665bTCKceIU2OR7HcgMsbXbn8yxPT0@dpg-crpqvaogph6c73a1pjv0-a.oregon-postgres.render.com/sit722diva
    ports:
      - "8001:8001"
    depends_on:
      - db

  inventory_management:
    build: ./inventory_management
    image: projectpthree2024/inventory_management
    container_name: inventory_management
    environment:
      - DATABASE_URL=postgresql://sit722diva_user:PW665bTCKceIU2OR7HcgMsbXbn8yxPT0@dpg-crpqvaogph6c73a1pjv0-a.oregon-postgres.render.com/sit722diva
    ports:
      - "8002:8002"
    depends_on:
      - db

#   db:
#     image: postgres:13
#     container_name: postgres_db
#     environment:
#       POSTGRES_USER: sit722_part3_mhy8_user
#       POSTGRES_PASSWORD: ZT5TqkZ6le6ejM7XJk2iKkLER9lMybFC
#       POSTGRES_DB: sit722_part3_mhy8
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
